/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.adrianob.view;

/**
 *
 * @author Administrador
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuBase = new javax.swing.JMenu();
        btnPessoas = new javax.swing.JMenuItem();
        btnPlanoDeContas = new javax.swing.JMenuItem();
        btnContaCorrente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnContasAPagar = new javax.swing.JMenuItem();
        btnContasAReceber = new javax.swing.JMenuItem();
        menuProc = new javax.swing.JMenu();
        btnLancaCaixa = new javax.swing.JMenuItem();
        btnRecebeConta = new javax.swing.JMenuItem();
        btnPagaConta = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        btnConsultaFluxo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setState(MAXIMIZED_BOTH);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuBase.setText("Cadastros");

        btnPessoas.setText("Pessoas");
        btnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoasActionPerformed(evt);
            }
        });
        menuBase.add(btnPessoas);

        btnPlanoDeContas.setText("Plano de contas");
        btnPlanoDeContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanoDeContasActionPerformed(evt);
            }
        });
        menuBase.add(btnPlanoDeContas);

        btnContaCorrente.setText("Conta Corrente");
        btnContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaCorrenteActionPerformed(evt);
            }
        });
        menuBase.add(btnContaCorrente);
        menuBase.add(jSeparator1);

        btnContasAPagar.setText("Contas a Pagar");
        btnContasAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContasAPagarActionPerformed(evt);
            }
        });
        menuBase.add(btnContasAPagar);

        btnContasAReceber.setText("Contas a Receber");
        btnContasAReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContasAReceberActionPerformed(evt);
            }
        });
        menuBase.add(btnContasAReceber);

        menuBar.add(menuBase);

        menuProc.setText("Processos");

        btnLancaCaixa.setText("Lançamento Caixa");
        btnLancaCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancaCaixaActionPerformed(evt);
            }
        });
        menuProc.add(btnLancaCaixa);

        btnRecebeConta.setText("Receber conta");
        btnRecebeConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecebeContaActionPerformed(evt);
            }
        });
        menuProc.add(btnRecebeConta);

        btnPagaConta.setText("Pagar Conta");
        btnPagaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagaContaActionPerformed(evt);
            }
        });
        menuProc.add(btnPagaConta);

        menuBar.add(menuProc);

        menuConsulta.setText("Consultas");

        btnConsultaFluxo.setText("Consulta Fluxo de Caixa");
        btnConsultaFluxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaFluxoActionPerformed(evt);
            }
        });
        menuConsulta.add(btnConsultaFluxo);

        menuBar.add(menuConsulta);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoasActionPerformed
        CadastroPessoa cp = new CadastroPessoa();
        cp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cp.setLocationRelativeTo(null);
        cp.setVisible(true);
    }//GEN-LAST:event_btnPessoasActionPerformed

    private void btnPlanoDeContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanoDeContasActionPerformed
        CadastroDeContaView cv = new CadastroDeContaView();
        cv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cv.setLocationRelativeTo(null);
        cv.setVisible(true);
    }//GEN-LAST:event_btnPlanoDeContasActionPerformed

    private void btnContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaCorrenteActionPerformed
        ContaCorrenteView ccv = new ContaCorrenteView();
        ccv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ccv.setLocationRelativeTo(null);
        ccv.setVisible(true);
    }//GEN-LAST:event_btnContaCorrenteActionPerformed

    private void btnLancaCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancaCaixaActionPerformed
        FluxoDeCaixaView fc = new FluxoDeCaixaView();
        fc.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        fc.setLocationRelativeTo(null);
        fc.setVisible(true);
    }//GEN-LAST:event_btnLancaCaixaActionPerformed

    private void btnContasAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContasAPagarActionPerformed
        ContaPagarView cp = new ContaPagarView();
        cp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cp.setLocationRelativeTo(null);
        cp.setVisible(true);
    }//GEN-LAST:event_btnContasAPagarActionPerformed

    private void btnContasAReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContasAReceberActionPerformed
        ContaReceberView cr = new ContaReceberView();
        cr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cr.setLocationRelativeTo(null);
        cr.setVisible(true);
    }//GEN-LAST:event_btnContasAReceberActionPerformed

    private void btnRecebeContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecebeContaActionPerformed
        ReceberContaView rcv = new ReceberContaView();
        rcv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rcv.setLocationRelativeTo(null);
        rcv.setVisible(true);
    }//GEN-LAST:event_btnRecebeContaActionPerformed

    private void btnPagaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagaContaActionPerformed
        PagarContaView cpv = new PagarContaView();
        cpv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cpv.setLocationRelativeTo(null);
        cpv.setVisible(true);
    }//GEN-LAST:event_btnPagaContaActionPerformed

    private void btnConsultaFluxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaFluxoActionPerformed
        ConsultaFluxoDeCaixa cpv = new ConsultaFluxoDeCaixa();
        cpv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cpv.setLocationRelativeTo(null);
        cpv.setVisible(true);
    }//GEN-LAST:event_btnConsultaFluxoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnConsultaFluxo;
    private javax.swing.JMenuItem btnContaCorrente;
    private javax.swing.JMenuItem btnContasAPagar;
    private javax.swing.JMenuItem btnContasAReceber;
    private javax.swing.JMenuItem btnLancaCaixa;
    private javax.swing.JMenuItem btnPagaConta;
    private javax.swing.JMenuItem btnPessoas;
    private javax.swing.JMenuItem btnPlanoDeContas;
    private javax.swing.JMenuItem btnRecebeConta;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBase;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuProc;
    // End of variables declaration//GEN-END:variables
}
